### ISSUE TITLE
作者,这个错误怎么弄

### ISSUE THREAD

**Issue by 3151036158** [RayTale/Ray#32]
账户1的初始余额为0
账户2的初始余额为0
Please enter the number of executions
3
warn: Microsoft.Orleans.Networking[0]
      Exception reading message Response S127.0.0.1:30000:0*grn/5C399409/00000001@3f666ab7->*cli/492b42bc@871399aa #6:  from remote endpoint 127.0.0.1:30000 to local endpoint 127.0.0.1:57243: System.IO.FileNotFoundException: Could not load file or assembly 'Ray.Core, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
      File name: 'Ray.Core, Culture=neutral, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
         at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
         at Orleans.Runtime.CachedTypeResolver.<>c__DisplayClass7_0.<TryPerformUncachedTypeResolution>g__ResolveAssembly|0(AssemblyName assemblyName)
         at System.TypeNameParser.ResolveAssembly(String asmName, Func`2 assemblyResolver, Boolean throwOnError, StackCrawlMark& stackMark)
         at System.TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
         at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
         at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
         at Orleans.Runtime.CachedTypeResolver.TryPerformUncachedTypeResolution(String fullName, Type& type, Assembly[] assemblies)
         at Orleans.Runtime.CachedTypeResolver.TryPerformUncachedTypeResolution(String name, Type& type)
         at Orleans.Runtime.CachedTypeResolver.TryResolveType(String name, Type& type)
         at Orleans.Serialization.TypeSerializer.GetTypeFromName(String assemblyQualifiedTypeName, Boolean throwOnError)
         at Orleans.Serialization.TypeSerializer.GetTypeFromTypeKey(TypeKey key, Boolean throwOnError)
         at Orleans.Serialization.ILBasedExceptionSerializer.Deserialize(Type expectedType, IDeserializationContext outerContext)
         at Orleans.Serialization.ILBasedSerializer.Deserialize(Type expectedType, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Serialization.SerializationManager.DeserializeInner(Type expected, IDeserializationContext context)
         at Orleans.Serialization.BuiltInTypes.DeserializeOrleansResponse(Type expected, IDeserializationContext context)
         at Orleans.Serialization.SerializationManager.DeserializeInner[TContext,TReader](SerializationManager sm, Type expected, TContext context, TReader reader)
         at Orleans.Runtime.Messaging.MessageSerializer.OrleansSerializer`1.Deserialize(ReadOnlySequence`1 input, T& value)
         at Orleans.Runtime.Messaging.MessageSerializer.TryRead(ReadOnlySequence`1& input, Message& message)
         at Orleans.Runtime.Messaging.Connection.ProcessIncoming()

**Comment by u-less** [comment]
@3151036158 修正的代码已经提交了,这个错误是AppDomain导致的,已经替换.

**Comment by 3151036158** [comment]
问题依旧呢

**Comment by u-less** [comment]
@3151036158 上次有修改遗漏的地方，现在测试已经通过了

**Comment by 3151036158** [comment]
info: Ray.EventBus.RabbitMQ.ConsumerManager[0]
      EventBus Background Service is disposing.
fail: Orleans.Runtime.Scheduler.OrleansTaskScheduler[101231]
      QueueWorkItem was called on a non-null context [SystemTarget: S127.0.0.1:9000:312110138*stg/13/0000000d@S0000000d] but there is no valid WorkItemGroup for it.
Unhandled exception. Microsoft.AspNetCore.Connections.AddressInUseException: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
 ---> System.Net.Sockets.SocketException (10048): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)


不可以改别的端口吗 我试了一堆 都是这个错误

**Comment by u-less** [comment]
@3151036158 Orleans的配置里可以改端口
